version: '3.8'

services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6388:6388
    volumes:
      - redis-data:/data

  app:
    build: .
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  mongo-data:
  redis-data:




# The bind mount mechanism allows changes in the host directory to be immediately reflected inside the container, and vice versa.